a.out: main.cpp StackOfIntegers.cpp StackOfIntegers.h MyEmptyStackException.cpp MyEmptyStackException.h
	g++ -Wall -std=c++11 -o a.out main.cpp StackOfIntegers.cpp StackOfIntegers.h MyEmptyStackException.cpp MyEmptyStackException.h

clean:
	rm a.out
